### ISSUE TITLE
8. Command Auto-complete

### ISSUE THREAD

**Issue by thomasmerz** [samsquire/ideas#40]
This is also a nice solution for bash which uses fish-shell: https://github.com/nevesnunes/sh-manpage-completions

**Comment by thomasmerz** [comment]
@samsquire , did you notice this? Or shall I close this "issue"?

**Comment by samsquire** [comment]
Sorry Thomas I've not been on a computer for a while. I will add your suggestion to existing section when I get a chance on a real computer. Or if you're willing to create a PR I'll merge it in straight away!

**Comment by thomasmerz** [comment]
@samsquire , here we go: PR https://github.com/samsquire/ideas/pull/43 😄
